# Generated by Django 3.2.3 on 2022-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmIMG', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
