# Generated by Django 3.2.3 on 2022-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itmIMG',
            field=models.ImageField(null=True, upload_to='0_ShopIems/'),
        ),
    ]
