# Generated by Django 4.0.2 on 2022-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strore_app', '0002_alter_items_itmimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.EmailField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
