# Generated by Django 4.0.2 on 2022-03-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strore_app', '0003_subscribe_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='describe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
