# Generated by Django 4.0.2 on 2022-03-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strore_app', '0004_items_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
